name: JadGens
version: ${project.version}
main: ml.jadss.jadgens.JadGens
load: STARTUP
authors: [Jadss_pt]
softdepend: [Vault, PlaceHolderAPI, PlayertPoints]
description: a generators plugin! hope you like it!
website: jadss.ml
commands:
  JadGens:
    usage: /<command>
    description: Main command of the plugin JadGens!